name: air_sync
description: "AirSync - Gestão de empresas de climatização"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  dio: ^5.7.0
  flutter_dotenv: ^5.1.0
  get_storage: ^2.1.1
  sqflite: ^2.3.3
  path: ^1.9.0
  connectivity_plus: ^6.0.4
  url_launcher: ^6.3.1
  intl: ^0.20.2
  logger: ^2.3.0
  equatable: ^2.0.5
  collection: ^1.18.0
  google_fonts: ^6.2.1
  package_info_plus: ^8.0.2
  image_picker: ^1.1.2
  file_picker: ^8.1.2
  signature: ^5.3.0
  mobile_scanner: ^5.1.1
  flutter_animate: ^4.5.0
  uuid: ^4.5.1
  dio_smart_retry: ^6.0.0
  pretty_dio_logger: ^1.4.0
  responsive_framework: ^1.3.1
  json_annotation: ^4.9.0
  mime: ^1.0.5
  dartz: ^0.10.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  json_serializable: ^6.9.3
  mocktail: ^1.0.3
  dio_http_mock_adapter: ^0.5.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/lottie/
    - .env.example
